#!/bin/bash
# vim:set et sw=2:

set -e

if ! type git >/dev/null 2>&1; then
 echo "Git is not installed." 
 exit 1
fi

destination="${1-.harunou}"

git clone https://github.com/harunou/harunou.git "$destination"

cd "$destination"

.local/bin/harunou-config setup-repo "$(pwd)"
.local/bin/harunou-config find . -print0 | sed "s/\x0\.\//\x0/g;s/^\.\///" | xargs -0 tar -cf - | .local/bin/harunou-config tar -xf -
