name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - master
      
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Upload file to GCS with Cache-Control
        run: |
          cp ./install ./stall
          gsutil -h "Cache-Control:no-cache, max-age=0" cp ./stall gs://www.harunou.in/
