name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - master
      
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Upload file to GCS
        run: |
          cp ./install ./stall
          gsutil cp ./stall gs://your-gcs-bucket/path/in/bucket/
